version: '3.8'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '5000:5000'
      - '9229:9229'
    command: npm run start:dev
    depends_on:
      - mongodb
    restart: always
  mongodb:
    container_name: mongodb
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    restart: unless-stopped
volumes:
  dbdata6: